services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hashhash
      POSTGRES_DB: db
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hashhash
      POSTGRES_DB: db
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  auth-service:
    build:
      context: ../auth-service
    container_name: auth-service
    env_file:
      - ../auth-service/.env
    depends_on:
      auth-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - mynetwork
    ports:
      - "50051:50051"
    restart: unless-stopped


  user-service:
    build:
      context: ../user-service
    container_name: user-service
    env_file:
      - ../user-service/.env
    depends_on:
      user-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - mynetwork
    ports:
      - "50052:50052"
    restart: unless-stopped


  api-gateway:
    build:
      context: ../api-gateway
    container_name: api-gateway
    env_file:
      - ../api-gateway/.env
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - mynetwork
    ports:
      - "8080:8080"
    restart: unless-stopped


  rabbitmq:
    image: rabbitmq:3-management  # Официальный образ RabbitMQ с Management Plugin
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Порт для приложений RabbitMQ
      - "15672:15672"  # Порт для веб-интерфейса управления
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Установите пользователя по умолчанию
      RABBITMQ_DEFAULT_PASS: guest  # Установите пароль по умолчанию
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl ping" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  auth-db-data:
  user-db-data:

networks:
  mynetwork:
    driver: bridge

