services:
  auth-service:
    build:
      context: ../auth-service
    container_name: auth-service
    env_file:
      - ../auth-service/.env
    depends_on:
      auth-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - mynetwork
    ports:
      - "50051:50051"
    restart: unless-stopped

  user-service:
    build:
      context: ../user-service
    container_name: user-service
    env_file:
      - ../user-service/.env
    depends_on:
      user-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - mynetwork
    ports:
      - "50052:50052"
    restart: unless-stopped

  todo-service:
    build:
      context: ../todo-service
    container_name: todo-service
    env_file:
      - ../todo-service/.env
    depends_on:
      todo-db:
        condition: service_healthy
    networks:
      - mynetwork
    ports:
      - "50053:50053"
    restart: unless-stopped

  push-service:
    build:
      context: ../push-service
    container_name: push-service
    env_file:
      - ../push-service/.env
    networks:
      - mynetwork
    ports:
      - "50054:50054"
    restart: unless-stopped

  api-gateway:
    build:
      context: ../api-gateway
    container_name: api-gateway
    env_file:
      - ../api-gateway/.env
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - mynetwork
    ports:
      - "8080:8080"
    restart: unless-stopped

networks:
  mynetwork:
    driver: bridge
